packages:
  - "js/browser/crsqlite-wasm"
  - "js/browser/sandbox"
  - "js/browser/wa-crsqlite"
  - "deps/wa-sqlite"
  - "js/react"
  - "js/sync-reference/p2p"
  - "js/sync-reference/server-core"
  - "js/sync-reference/server-websocket"
  - "js/sync-reference/client-core"
  - "js/sync-reference/client-websocket"
  - "js/sync-reference/client-server-common"
  - "js/tests/xplat-tests"
  - "js/tests/nodeno-tests"
  - "js/tests/browser-tests"
  - "js/rx-tbl"
  - "js/node-allinone"
  - "js/xplat-api"
  - "js/tsbuild-all"
  - "js/examples/p2p-todomvc"
  - "js/examples/todomvc"
  - "js/examples/peer-server"
  - "js/examples/node"
  - "js/examples/basic-browser-setup"
  - "core"
  - "py/correctness"
