packages:
  - "js/wasm-esm/crsqlite"
  - "js/wasm-esm/sandbox"
  - "js/wasm-esm/wa-crsqlite"
  - "js/wasm-esm/wa-sqlite"
  - "js/sync-reference/webrtc"
  - "js/sync-reference/whole-db"
  - "js/sync-reference/server"
  - "js/tests/xplat-tests"
  - "js/tests/nodeno-tests"
  - "js/tests/browser-tests"
  - "js/rx-tbl"
  - "js/node-allinone"
  - "js/xplat-api"
  - "js/tsbuild-all"
  - "js/examples/p2p-todomvc"
  - "js/examples/todomvc"
  - "js/examples/peer-server"
  - "js/examples/node"
  - "js/examples/basic-browser-setup"
  - "native"
  - "py/correctness"
