packages:
  - "js/wasm-esm/crsqlite"
  - "js/wasm-esm/examples"
  - "js/wasm-esm/sandbox"
  - "js/wasm-esm/wa-crsqlite"
  - "js/wasm-esm/wa-sqlite"
  - "js/network/webrtc"
  - "js/replicators/whole-db"
  - "js/tests/xplat-tests"
  - "js/tests/nodeno-tests"
  - "js/tests/browser-tests"
  - "js/rx/table-based"
  - "js/sync-server"
  - "js/nodeno/allinone"
  - "js/nodeno/examples"
  - "js/xplat-api"
  - "js/tsbuild-all"
  - "js/examples/p2p-todomvc"
  - "js/examples/todomvc"
  - "js/examples/peer-server"
  - "native"
  - "py/correctness"
