packages:
  - "wasm-esm/crsqlite"
  - "wasm-esm/examples"
  - "wasm-esm/sandbox"
  - "network/webrtc"
  - "replicators/whole-db"
  - "replicators/browser-tests"
  - "replicators/xplat-tests"
  - "replicators/nodeno-tests"
  - "rx/table-based"
  - "nodeno/allinone"
  - "nodeno/examples"
  - "xplat-api"
