packages:
  - "wasm-esm/crsqlite"
  - "wasm-esm/examples"
  - "wasm-esm/sandbox"
  - "wasm-esm/wa-crsqlite"
  - "wasm-esm/wa-sqlite"
  - "network/webrtc"
  - "replicators/whole-db"
  - "tests/xplat-tests"
  - "tests/nodeno-tests"
  - "tests/browser-tests"
  - "rx/table-based"
  - "nodeno/allinone"
  - "nodeno/examples"
  - "xplat-api"
  - "tsbuild-all"
  - "examples/p2p-todomvc"
  - "examples/peer-server"
