packages:
  - "wasm-esm/crsqlite"
  - "wasm-esm/examples"
  - "wasm-esm/sandbox"
  - "network/webrtc"
  - "replicators/whole-db"
  - "replicators/browser-tests"
  - "node-deno/allinone"
  - "node-deno/examples"
