on:
  push:
  pull_request:
    types: [opened, edited]
name: "c-valgrind"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          #- os: windows-2022
          #- os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: Build Tests
        run: |
          cd core
          make dist/test

      - name: Install valgrind
        run: sudo apt install -y valgrind

      - name: Run Valgrind
        run: |
          cd core
          valgrind dist/test
