on: push
name: "py-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false # python just needs the loadable extension

      - name: Make loadable
        run: |
          cd native
          make loadable

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Install SQLite
        run: conda install sqlite

      # - name: Install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Pip Deps
        run: cd py/correctness && pip install -e .

      - name: Test
        run: cd py/correctness && pytest
